export const currencies = [
  { code: "USD", name: "US Dollar", symbol: "$", flag: "🇺🇸" },
  { code: "EUR", name: "Euro", symbol: "EUR", flag: "🇪🇺" },
  { code: "GBP", name: "British Pound", symbol: "GBP", flag: "🇬🇧" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", flag: "🇨🇦" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", flag: "🇨🇭" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", flag: "🇦🇺" },
  { code: "JPY", name: "Japanese Yen", symbol: "JPY", flag: "🇯🇵" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", flag: "🇦🇷" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs", flag: "🇧🇴" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", flag: "🇧🇷" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", flag: "🇧🇿" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", flag: "🇨🇱" },
  { code: "COP", name: "Colombian Peso", symbol: "$", flag: "🇨🇴" },
  { code: "CRC", name: "Costa Rican Colon", symbol: "CRC", flag: "🇨🇷" },
  { code: "CUP", name: "Cuban Peso", symbol: "$", flag: "🇨🇺" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", flag: "🇩🇴" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", flag: "🇬🇹" },
  { code: "GYD", name: "Guyanese Dollar", symbol: "G$", flag: "🇬🇾" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", flag: "🇭🇳" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", flag: "🇭🇹" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", flag: "🇲🇽" },
  { code: "NIO", name: "Nicaraguan Cordoba", symbol: "C$", flag: "🇳🇮" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", flag: "🇵🇦" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", flag: "🇵🇪" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "Gs", flag: "🇵🇾" },
  { code: "SRD", name: "Surinamese Dollar", symbol: "SRD", flag: "🇸🇷" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", flag: "🇺🇾" },
  { code: "VES", name: "Venezuelan Bolivar", symbol: "Bs", flag: "🇻🇪" },
] as const

export type CurrencyCode = (typeof currencies)[number]["code"]
export const currencyCodes = currencies.map((currency) => currency.code)
