export const currencies = [
  { code: "ALL", name: "Albanian Lek", symbol: "L", flag: "🇦🇱" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", flag: "🇩🇿" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", flag: "🇦🇴" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", flag: "🇦🇷" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", flag: "🇦🇲" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", flag: "🇦🇺" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", flag: "🇦🇿" },
  { code: "BHD", name: "Bahraini Dinar", symbol: "BD", flag: "🇧🇭" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", flag: "🇧🇩" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", flag: "🇧🇹" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", flag: "🇧🇾" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", flag: "🇧🇿" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs", flag: "🇧🇴" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", flag: "🇧🇦" },
  { code: "BWP", name: "Botswana Pula", symbol: "P", flag: "🇧🇼" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", flag: "🇧🇷" },
  { code: "GBP", name: "British Pound", symbol: "GBP", flag: "🇬🇧" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", flag: "🇧🇳" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", flag: "🇧🇬" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", flag: "🇧🇮" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", flag: "🇰🇭" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", flag: "🇨🇦" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", flag: "🇨🇻" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA", flag: "🌍" },
  { code: "XPF", name: "CFP Franc", symbol: "₣", flag: "🌊" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", flag: "🇨🇱" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", flag: "🇨🇳" },
  { code: "COP", name: "Colombian Peso", symbol: "$", flag: "🇨🇴" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", flag: "🇰🇲" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC", flag: "🇨🇩" },
  { code: "CRC", name: "Costa Rican Colon", symbol: "CRC", flag: "🇨🇷" },
  { code: "CUP", name: "Cuban Peso", symbol: "$", flag: "🇨🇺" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", flag: "🇨🇿" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", flag: "🇩🇰" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", flag: "🇩🇯" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", flag: "🇩🇴" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£", flag: "🇪🇬" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", flag: "🇪🇷" },
  { code: "SZL", name: "Eswatini Lilangeni", symbol: "E", flag: "🇸🇿" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", flag: "🇪🇹" },
  { code: "EUR", name: "Euro", symbol: "EUR", flag: "🇪🇺" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", flag: "🇫🇯" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", flag: "🇬🇲" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", flag: "🇬🇪" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵", flag: "🇬🇭" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", flag: "🇬🇹" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", flag: "🇬🇳" },
  { code: "GYD", name: "Guyanese Dollar", symbol: "G$", flag: "🇬🇾" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", flag: "🇭🇰" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", flag: "🇭🇹" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", flag: "🇭🇳" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", flag: "🇭🇺" },
  { code: "ISK", name: "Icelandic Krona", symbol: "kr", flag: "🇮🇸" },
  { code: "INR", name: "Indian Rupee", symbol: "₹", flag: "🇮🇳" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", flag: "🇮🇩" },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", flag: "🇮🇷" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", flag: "🇮🇶" },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪", flag: "🇮🇱" },
  { code: "JPY", name: "Japanese Yen", symbol: "JPY", flag: "🇯🇵" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "JD", flag: "🇯🇴" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", flag: "🇰🇿" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", flag: "🇰🇪" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "KD", flag: "🇰🇼" },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "с", flag: "🇰🇬" },
  { code: "LAK", name: "Lao Kip", symbol: "₭", flag: "🇱🇦" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", flag: "🇱🇧" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", flag: "🇱🇸" },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", flag: "🇱🇷" },
  { code: "LYD", name: "Libyan Dinar", symbol: "LD", flag: "🇱🇾" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", flag: "🇲🇰" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", flag: "🇲🇬" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", flag: "🇲🇼" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", flag: "🇲🇾" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", flag: "🇲🇻" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", flag: "🇲🇷" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", flag: "🇲🇺" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", flag: "🇲🇽" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", flag: "🇲🇩" },
  { code: "MNT", name: "Mongolian Togrog", symbol: "₮", flag: "🇲🇳" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "DH", flag: "🇲🇦" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", flag: "🇲🇿" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", flag: "🇲🇲" },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$", flag: "🇳🇦" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", flag: "🇳🇵" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", flag: "🇳🇿" },
  { code: "NIO", name: "Nicaraguan Cordoba", symbol: "C$", flag: "🇳🇮" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", flag: "🇳🇬" },
  { code: "KPW", name: "North Korean Won", symbol: "₩", flag: "🇰🇵" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", flag: "🇳🇴" },
  { code: "OMR", name: "Omani Rial", symbol: "﷼", flag: "🇴🇲" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", flag: "🇵🇰" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", flag: "🇵🇦" },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", flag: "🇵🇬" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "Gs", flag: "🇵🇾" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", flag: "🇵🇪" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", flag: "🇵🇭" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", flag: "🇵🇱" },
  { code: "QAR", name: "Qatari Riyal", symbol: "QR", flag: "🇶🇦" },
  { code: "RON", name: "Romanian Leu", symbol: "lei", flag: "🇷🇴" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", flag: "🇷🇺" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", flag: "🇷🇼" },
  { code: "SAR", name: "Saudi Riyal", symbol: "SR", flag: "🇸🇦" },
  { code: "STN", name: "Sao Tome and Principe Dobra", symbol: "Db", flag: "🇸🇹" },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин", flag: "🇷🇸" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", flag: "🇸🇨" },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le", flag: "🇸🇱" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", flag: "🇸🇬" },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh", flag: "🇸🇴" },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", flag: "🇸🇧" },
  { code: "ZAR", name: "South African Rand", symbol: "R", flag: "🇿🇦" },
  { code: "KRW", name: "South Korean Won", symbol: "₩", flag: "🇰🇷" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "SSP", flag: "🇸🇸" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", flag: "🇱🇰" },
  { code: "SDG", name: "Sudanese Pound", symbol: "SDG", flag: "🇸🇩" },
  { code: "SRD", name: "Surinamese Dollar", symbol: "SRD", flag: "🇸🇷" },
  { code: "SYP", name: "Syrian Pound", symbol: "LS", flag: "🇸🇾" },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$", flag: "🇹🇼" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", flag: "🇹🇯" },
  { code: "THB", name: "Thai Baht", symbol: "฿", flag: "🇹🇭" },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", flag: "🇹🇴" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", flag: "🇸🇪" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", flag: "🇨🇭" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", flag: "🇹🇿" },
  { code: "TND", name: "Tunisian Dinar", symbol: "DT", flag: "🇹🇳" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", flag: "🇹🇷" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "m", flag: "🇹🇲" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", flag: "🇺🇬" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", flag: "🇺🇦" },
  { code: "AED", name: "United Arab Emirates Dirham", symbol: "د.إ", flag: "🇦🇪" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", flag: "🇺🇾" },
  { code: "USD", name: "US Dollar", symbol: "$", flag: "🇺🇸" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "so'm", flag: "🇺🇿" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", flag: "🇻🇺" },
  { code: "VES", name: "Venezuelan Bolivar", symbol: "Bs", flag: "🇻🇪" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", flag: "🇻🇳" },
  { code: "WST", name: "Samoan Tala", symbol: "WS$", flag: "🇼🇸" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA", flag: "🌍" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", flag: "🇾🇪" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", flag: "🇿🇲" },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$", flag: "🇿🇼" },
] as const

export type CurrencyCode = (typeof currencies)[number]["code"]
export const currencyCodes = currencies.map((currency) => currency.code)

export const currencyCountries: Partial<Record<CurrencyCode, readonly string[]>> = {
  AED: ["United Arab Emirates", "UAE"],
  AMD: ["Armenia"],
  AUD: ["Australia", "Kiribati", "Nauru", "Tuvalu"],
  AZN: ["Azerbaijan"],
  BDT: ["Bangladesh"],
  BHD: ["Bahrain"],
  BND: ["Brunei"],
  BTN: ["Bhutan"],
  CNY: ["China"],
  FJD: ["Fiji"],
  EUR: [
    "Andorra",
    "Austria",
    "Belgium",
    "Croatia",
    "Cyprus",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Monaco",
    "Netherlands",
    "Portugal",
    "San Marino",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Vatican City",
  ],
  GBP: ["United Kingdom", "England", "Scotland", "Wales", "Northern Ireland"],
  GEL: ["Georgia"],
  HKD: ["Hong Kong"],
  IDR: ["Indonesia"],
  ILS: ["Israel", "Palestine"],
  INR: ["India"],
  IQD: ["Iraq"],
  IRR: ["Iran"],
  JOD: ["Jordan"],
  JPY: ["Japan"],
  KGS: ["Kyrgyzstan"],
  KHR: ["Cambodia"],
  KPW: ["North Korea"],
  KRW: ["South Korea"],
  KWD: ["Kuwait"],
  KZT: ["Kazakhstan"],
  LAK: ["Laos"],
  LBP: ["Lebanon"],
  LKR: ["Sri Lanka"],
  MMK: ["Myanmar", "Burma"],
  MNT: ["Mongolia"],
  MVR: ["Maldives"],
  MYR: ["Malaysia"],
  NPR: ["Nepal"],
  NZD: ["New Zealand", "Cook Islands", "Niue", "Pitcairn Islands", "Tokelau"],
  OMR: ["Oman"],
  PGK: ["Papua New Guinea"],
  PHP: ["Philippines"],
  PKR: ["Pakistan"],
  QAR: ["Qatar"],
  RUB: ["Russia"],
  SAR: ["Saudi Arabia"],
  SBD: ["Solomon Islands"],
  SGD: ["Singapore"],
  SYP: ["Syria"],
  THB: ["Thailand"],
  TJS: ["Tajikistan"],
  TMT: ["Turkmenistan"],
  TOP: ["Tonga"],
  TRY: ["Turkey"],
  TWD: ["Taiwan"],
  USD: [
    "United States",
    "United States of America",
    "USA",
    "Ecuador",
    "El Salvador",
    "Timor-Leste",
    "Marshall Islands",
    "Micronesia",
    "Palau",
  ],
  UZS: ["Uzbekistan"],
  VUV: ["Vanuatu"],
  VND: ["Vietnam"],
  WST: ["Samoa"],
  XPF: ["French Polynesia", "New Caledonia", "Wallis and Futuna"],
  YER: ["Yemen"],
}
